version: "3.9"

services:
  auth:
    build:
      context: .
      dockerfile: infra/Dockerfile.auth
    container_name: auth-service
    ports:
      - "8001:8001"

  backend:
    build:
      context: .
      dockerfile: infra/Dockerfile.backend
    container_name: backend-service
    ports:
      - "8000:8000"
    depends_on:
      - auth

  jewelry-store:
    build:
      context: ./jewelry-store
      dockerfile: ../infra/Dockerfile.frontend
    container_name: jewelry-store
    ports:
      - "3000:3000"
    depends_on:
      - backend


