# שלב 1: התקנת aws-cli ו-snyk
FROM amazonlinux:2 as installer

# התקנת aws-cli
RUN yum update -y && \
    yum install -y unzip curl && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install --bin-dir /aws-cli-bin/

# התקנת snyk
RUN mkdir /snyk && cd /snyk && \
    curl https://static.snyk.io/cli/v1.666.0/snyk-linux -o snyk && \
    chmod +x snyk

# שלב 2: בניית Jenkins Agent מבוסס jenkins/agent
FROM jenkins/agent

# העתקת docker client (אם יש אימג' בשם docker עם docker מותקן)
COPY --from=docker /usr/local/bin/docker /usr/local/bin/

# העתקת aws-cli ו-snyk מהשלב הקודם
COPY --from=installer /aws-cli-bin/ /usr/local/bin/
COPY --from=installer /snyk/ /usr/local/bin/

USER root
RUN apt-get update && apt-get install -y python3 python3-pip

USER jenkins
