# Dockerfile.auth
FROM node:18

WORKDIR /app

# הקבצים מועתקים מתוך תיקיית השירות שה־context שלה מוגדר כ־auth-service
COPY package*.json ./
RUN npm install

COPY . .
EXPOSE 3001
CMD ["npm", "start"]




