# Dockerfile.backend
FROM node:18

# הגדרת תיקיית עבודה
WORKDIR /app

# העתק package.json ו־package-lock.json מהתיקייה הראשית
COPY ../package*.json ./

# התקנת תלויות
RUN npm install

# העתקת קבצי השירות עצמו
COPY ./backend-service ./ 

# הגדרת הפקודה להפעלת השירות
CMD ["npm", "start"]


