FROM node:18
WORKDIR /app

# העתקת package.json והתקנת dependencies
COPY backend/package*.json ./
RUN npm install

# העתקת הקוד
COPY backend/. .

# חשיפת פורט 5000 (או מה שהאפליקציה שלך משתמשת)
EXPOSE 5000

# הפעלת ה-backend
CMD ["npm", "start"]

